spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-218-92-155.compute-1.amazonaws.com/d1umtsgaap27l7
  username: xyzccujcbajfll
  password: 2580d8a8877d7d9973cb4b150181911c960fcb087bfcfba5e7aaa21ca99cdbe2
  platform: postgres
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

jwt:
  secret-key: fast_campus.sns-applications-2022.secret_key
  # 30day
  # 24*60*60*30
  token.expired-time-ms: 2592000000

spring.redis.url: redis://:p3ee7ac9e8116d6de553d0b9960481d25fafad9e0cf4a3c627d7a3af20c2cb7e6@ec2-54-88-4-125.compute-1.amazonaws.com:10109

spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="r2rj2fh0" password="e_BnIr6ESAbpmuu7L7XugsMNmYlx3eFq";
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      group-id: notification
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: r2rj2fh0-notification

